document.addEventListener('DOMContentLoaded', () => { setTimeout(() => { const splash = document.getElementById('splash-screen'); if (splash) { splash.style.opacity = '0'; splash.style.visibility = 'hidden'; setTimeout(() => splash.remove(), 600); } }, 2000); const dynamicView = document.getElementById('dynamic-view'); const views = { home: dynamicView.innerHTML, // SEARCH VIEW: YouTube Import button added near Search Title search: `
Search
Recently Searched
`, library: `
Library`, premium: `
Octave Premium
Ad-free background listening activated.
` }; document.querySelectorAll('.nav-item').forEach(item => { item.addEventListener('click', () => { document.querySelector('.nav-item.active').classList.remove('active'); item.classList.add('active'); const tab = item.getAttribute('data-tab'); if (tab === 'home') { dynamicView.innerHTML = views.home; window.renderHome(); bindHomeModals(); } else { dynamicView.innerHTML = views[tab]; if (tab === 'search') bindSearch(); if (tab === 'library') renderLibrary(); } }); }); handleBravePrompt(); bindHomeModals(); window.renderHome(); document.querySelector('.mini-inner').addEventListener('click', () => document.getElementById('full-player').classList.add('active')); document.getElementById('close-fp').addEventListener('click', () => document.getElementById('full-player').classList.remove('active')); document.getElementById('close-track-options').addEventListener('click', () => document.getElementById('track-options-modal').classList.remove('active')); document.getElementById('close-select-playlist').addEventListener('click', () => document.getElementById('select-playlist-modal').classList.remove('active')); }); document.body.addEventListener('click', async (e) => { if (e.target.closest('#menu-btn')) { document.getElementById('side-menu').classList.add('active'); document.getElementById('menu-backdrop').classList.add('active'); } if (e.target.closest('#close-menu') || e.target.closest('#menu-backdrop')) { document.getElementById('side-menu').classList.remove('active'); document.getElementById('menu-backdrop').classList.remove('active'); } if (e.target.closest('#open-yt-import')) { document.getElementById('yt-import-modal').classList.add('active'); } const pageBtn = e.target.closest('[data-page]'); if (pageBtn) { document.getElementById('side-menu').classList.remove('active'); document.getElementById('menu-backdrop').classList.remove('active'); const url = pageBtn.getAttribute('data-page'); const dynamicView = document.getElementById('dynamic-view'); dynamicView.innerHTML = '
'; try { const r = await fetch(url); const html = await r.text(); const parser = new DOMParser(); const doc = parser.parseFromString(html, 'text/html'); dynamicView.innerHTML = doc.querySelector('.mobile-app').innerHTML; const backBtn = dynamicView.querySelector('a[href="index.html"]'); if (backBtn) { backBtn.addEventListener('click', (ev) => { ev.preventDefault(); document.querySelector('.nav-item[data-tab="home"]').click(); }); } } catch (err) { dynamicView.innerHTML = '
Failed to load.
'; } } }); document.getElementById('export-vault-btn').addEventListener('click', () => { document.getElementById('side-menu').classList.remove('active'); document.getElementById('menu-backdrop').classList.remove('active'); window.exportVault(); }); document.getElementById('import-vault-btn').addEventListener('click', () => { document.getElementById('import-vault-input').click(); }); document.getElementById('import-vault-input').addEventListener('change', window.importVault); const fpPanel = document.getElementById('fp-overlay-panel'); const fpContent = document.getElementById('fp-overlay-content'); const fpTitle = document.getElementById('fp-overlay-title'); document.getElementById('close-fp-overlay').addEventListener('click', () => fpPanel.classList.remove('active')); // STATIC LYRICS WITH FONT PICKER document.getElementById('fp-lyrics-btn').addEventListener('click', async () => { if (window.OCTAVE.currentIndex < 0) return; fpTitle.innerText = 'Lyrics'; fpContent.innerHTML = '
'; fpPanel.classList.add('active'); const track = window.OCTAVE.queue[window.OCTAVE.currentIndex]; const html = await window.fetchLyrics(track.author, track.title); const fonts = [ { name: 'Modern', css: 'Plus Jakarta Sans' }, { name: 'Clean', css: 'Inter' }, { name: 'Classic', css: 'Lora' }, { name: 'Elegant', css: 'Playfair Display' }, { name: 'Bold', css: 'Montserrat' }, { name: 'Heavy', css: 'Kanit' }, { name: 'Typewriter', css: 'Roboto Mono' }, { name: 'Cursive', css: 'Dancing Script' }, { name: 'Sharp', css: 'Oswald' }, { name: 'Impact', css: 'Bebas Neue' } ]; let fontHeader = `
`; fonts.forEach(f => { const activeClass = window.OCTAVE.selectedFont === f.css ? 'active' : ''; fontHeader += `
${f.name}
`; }); fontHeader += `
`; fpContent.innerHTML = fontHeader + `
${html}
`; }); window.setLyricsFont = (fontCss, el) => { window.OCTAVE.selectedFont = fontCss; localStorage.setItem('octave_font', fontCss); document.querySelectorAll('.font-option').forEach(opt => opt.classList.remove('active')); el.classList.add('active'); const container = document.getElementById('lyrics-content'); if (container && container.firstChild) { container.firstChild.style.fontFamily = `'${fontCss}', sans-serif`; } }; window.renderArtistPage = async (artistName) => { document.getElementById('full-player').classList.remove('active'); document.getElementById('fp-overlay-panel').classList.remove('active'); const dynamicView = document.getElementById('dynamic-view'); dynamicView.innerHTML = '
'; const profile = await window.fetchFullArtistProfile(artistName); let tracksHTML = ''; if (profile.tracks.length > 0) { profile.tracks.forEach((track, index) => { tracksHTML += `

${window.escapeHTML(track.title)}
${window.escapeHTML(track.author)}
`; }); } else { tracksHTML = '
No tracks found.
'; } const bannerStyle = profile.banner ? `background-image: url('${profile.banner}'); background-size: cover; background-position: center;` : `background: linear-gradient(135deg, var(--bg-deep), var(--glass-bg));`; dynamicView.innerHTML = `
${window.escapeHTML(profile.name)}
${window.escapeHTML(profile.bio)}
Top Tracks${tracksHTML}
`; if (profile.tracks.length > 0) { document.querySelectorAll('.artist-track-item').forEach((node, idx) => { node.addEventListener('click', () => { window.OCTAVE.queue = [...profile.tracks]; window.playTrackByIndex(idx); }); }); } }; document.getElementById('fp-artist').addEventListener('click', () => { if (window.OCTAVE.currentIndex < 0) return; const track = window.OCTAVE.queue[window.OCTAVE.currentIndex]; window.renderArtistPage(track.author); }); document.getElementById('fp-queue-btn').addEventListener('click', () => { if (window.OCTAVE.currentIndex < 0) return; fpTitle.innerText = 'Up Next'; fpContent.innerHTML = ''; fpPanel.classList.add('active'); const q = window.OCTAVE.queue; const curr = window.OCTAVE.currentIndex; for (let i = curr; i < q.length; i++) { const track = q[i]; const isPlaying = i === curr; const el = document.createElement('div'); el.style.cssText = `display: flex; align-items: center; gap: 14px; padding: 12px; background: ${isPlaying ? 'rgba(30,215,96,0.1)' : 'var(--bg-surface)'}; border-radius: 8px; margin-bottom: 12px; border: ${isPlaying ? '1px solid var(--accent)' : '1px solid transparent'};`; el.innerHTML = `

${window.escapeHTML(track.title)}
${window.escapeHTML(track.author)}
${isPlaying ? '' : ''} `; fpContent.appendChild(el); } }); document.getElementById('opt-sleep-timer').addEventListener('click', () => { document.getElementById('track-options-modal').classList.remove('active'); document.getElementById('timer-modal').classList.add('active'); }); document.getElementById('close-timer').addEventListener('click', () => document.getElementById('timer-modal').classList.remove('active')); if (document.getElementById('fp-options')) { document.getElementById('fp-options').addEventListener('click', () => { if (window.OCTAVE && window.OCTAVE.currentIndex >= 0) { openTrackOptions(window.OCTAVE.queue[window.OCTAVE.currentIndex]); } }); } window.renderHome = () => { const hour = new Date().getHours(); let greeting = 'Good evening'; if (hour >= 5 && hour < 12) greeting = 'Good morning'; else if (hour >= 12 && hour < 17) greeting = 'Good afternoon'; if (document.getElementById('time-greeting')) document.getElementById('time-greeting').textContent = greeting; const recentGrid = document.getElementById('home-recent-grid'); const playlistsDiv = document.getElementById('home-playlists'); if (!recentGrid || !playlistsDiv) return; if (window.OCTAVE.recentPlayed.length > 0) { recentGrid.innerHTML = ''; window.OCTAVE.recentPlayed.forEach(track => { const el = document.createElement('div'); el.className = 'square-card'; el.innerHTML = `
${window.escapeHTML(track.title)}
`; el.addEventListener('click', () => window.playTrack(track)); recentGrid.appendChild(el); }); } if (window.fetchTrendingMusic) window.fetchTrendingMusic(); const recsGrid = document.getElementById('home-recs-grid'); if (recsGrid) { if (window.OCTAVE.dailyRecs && window.OCTAVE.dailyRecs.tracks.length > 0) { recsGrid.innerHTML = ''; window.OCTAVE.dailyRecs.tracks.forEach(track => { const el = document.createElement('div'); el.className = 'square-card'; el.innerHTML = `
${window.escapeHTML(track.title)}
`; el.addEventListener('click', () => window.playTrack(track)); recsGrid.appendChild(el); }); } } if (window.fetchDailyRecommendations) window.fetchDailyRecommendations(); const likedCount = Object.keys(window.OCTAVE.liked).length; playlistsDiv.innerHTML = `

Auto-DJ Discover Mix
Endless tracks based on taste

Liked Songs
${likedCount} tracks saved
`; document.getElementById('open-discover-mix').addEventListener('click', () => { if (window.generateDiscoverMix) window.generateDiscoverMix(); }); document.getElementById('open-liked-songs').addEventListener('click', window.renderLikedSongs); Object.keys(window.OCTAVE.playlists).forEach(plName => { const el = document.createElement('div'); el.className = 'list-item'; el.innerHTML = `

${window.escapeHTML(plName)}
${window.OCTAVE.playlists[plName].length} tracks
`; el.addEventListener('click', () => window.renderPlaylistDetail(plName)); playlistsDiv.appendChild(el); }); }; function renderLibrary() { const lib = document.getElementById('lib-playlists'); if (!lib) return; lib.innerHTML = Object.keys(window.OCTAVE.playlists).length > 0 ? '' : '
Create or import a playlist.
'; Object.keys(window.OCTAVE.playlists).forEach(plName => { const el = document.createElement('div'); el.className = 'list-item'; el.innerHTML = `

${window.escapeHTML(plName)}
${window.OCTAVE.playlists[plName].length} tracks
`; el.addEventListener('click', () => window.renderPlaylistDetail(plName)); lib.appendChild(el); }); } function buildTrackItem(track) { const el = document.createElement('div'); el.className = 'list-item'; el.innerHTML = `

${window.escapeHTML(track.title)}
${window.escapeHTML(track.author)}
`; el.addEventListener('click', () => window.playTrack(track)); return el; } function bindSearch() { const input = document.getElementById('searchInput'); const resContainer = document.getElementById('searchResults'); const recentList = document.getElementById('search-recent-list'); if (recentList) { if (window.OCTAVE.recentSearches.length === 0) { recentList.innerHTML = '
No searches.
'; } else { recentList.innerHTML = ''; window.OCTAVE.recentSearches.forEach(track => recentList.appendChild(buildTrackItem(track))); } } let timer; input.addEventListener('input', (e) => { clearTimeout(timer); const query = e.target.value.trim(); if (!query) { document.getElementById('search-default-view').style.display = 'block'; Array.from(resContainer.children).forEach(c => { if (c.id !== 'search-default-view') c.remove(); }); return; } document.getElementById('search-default-view').style.display = 'none'; Array.from(resContainer.children).forEach(c => { if (c.id !== 'search-default-view') c.remove(); }); const loader = document.createElement('div'); loader.innerHTML = '
'; resContainer.appendChild(loader); timer = setTimeout(async () => { const results = await window.performSearch(query); loader.remove(); if (results.length === 0) { const empty = document.createElement('div'); empty.className = 'empty-state-text'; empty.innerText = 'No results.'; resContainer.appendChild(empty); return; } results.slice(0, 15).forEach(track => resContainer.appendChild(buildTrackItem(track))); }, 500); }); } function handleBravePrompt() { if (!localStorage.getItem('bravePromptShown')) setTimeout(() => document.getElementById('brave-modal').classList.add('active'), 1500); const dismissBrave = () => { localStorage.setItem('bravePromptShown', 'true'); document.getElementById('brave-modal').classList.remove('active'); }; document.getElementById('close-brave').addEventListener('click', dismissBrave); document.getElementById('get-brave').addEventListener('click', dismissBrave); } function bindHomeModals() { const openPl = document.getElementById('open-create-playlist'); const plModal = document.getElementById('playlist-modal'); if (openPl) openPl.addEventListener('click', () => plModal.classList.add('active')); document.getElementById('close-playlist').addEventListener('click', () => plModal.classList.remove('active')); document.getElementById('save-playlist').addEventListener('click', () => { const name = document.getElementById('playlist-name').value.trim(); if (name !== '' && !window.OCTAVE.playlists[name]) { window.OCTAVE.playlists[name] = []; window.saveCache(); document.getElementById('playlist-name').value = ''; plModal.classList.remove('active'); window.renderHome(); } }); } document.getElementById('opt-like-track').addEventListener('click', () => { if (window.OCTAVE.activeTrackForOptions) { window.toggleLike(window.OCTAVE.activeTrackForOptions); document.getElementById('track-options-modal').classList.remove('active'); } }); document.getElementById('opt-add-playlist').addEventListener('click', () => { document.getElementById('track-options-modal').classList.remove('active'); const plModal = document.getElementById('select-playlist-modal'); const list = document.getElementById('playlist-selection-list'); if (Object.keys(window.OCTAVE.playlists).length === 0) { list.innerHTML = '
No playlists.
'; } else { list.innerHTML = ''; Object.keys(window.OCTAVE.playlists).forEach(plName => { const el = document.createElement('div'); el.className = 'drawer-item'; el.innerHTML = ` ${window.escapeHTML(plName)}`; el.addEventListener('click', () => { window.OCTAVE.playlists[plName].push(window.OCTAVE.activeTrackForOptions); window.saveCache(); plModal.classList.remove('active'); if (window.renderPlaylistDetail && document.querySelector('h1').textContent === plName) window.renderPlaylistDetail(plName); }); list.appendChild(el); }); } plModal.classList.add('active'); }); document.getElementById('start-yt-import')?.addEventListener('click', async () => { const urlInput = document.getElementById('yt-playlist-url').value.trim(); if (!urlInput) return; let playlistId = ''; try { const urlObj = new URL(urlInput); playlistId = urlObj.searchParams.get('list'); } catch (e) { if (urlInput.startsWith('PL') && urlInput.length > 15) { playlistId = urlInput; } } if (!playlistId) { alert("Invalid URL."); return; } const btn = document.getElementById('start-yt-import'); btn.innerHTML = ''; btn.disabled = true; let success = false; for (let i = 0; i < window.INVIDIOUS.length; i++) { const base = window.INVIDIOUS[(window.invIdx + i) % window.INVIDIOUS.length]; const controller = new AbortController(); const timeoutId = setTimeout(() => controller.abort(), 5000); try { const r = await fetch(`${base}/api/v1/playlists/${playlistId}`, { signal: controller.signal }); clearTimeout(timeoutId); if (r.ok) { const data = await r.json(); if (data.videos && data.videos.length > 0) { let finalName = data.title || "Imported"; let count = 1; while (window.OCTAVE.playlists[finalName]) { finalName = `${data.title} (${count})`; count++; } window.OCTAVE.playlists[finalName] = data.videos.map(v => ({ videoId: v.videoId, title: v.title, author: v.author, thumb: (v.videoThumbnails && v.videoThumbnails.length > 0) ? v.videoThumbnails[0].url : '' })); window.saveCache(); success = true; alert(`Imported ${data.videos.length} tracks!`); document.getElementById('yt-import-modal').classList.remove('active'); document.getElementById('yt-playlist-url').value = ''; if (document.querySelector('.nav-item.active').getAttribute('data-tab') === 'library') { renderLibrary(); } break; } } } catch (e) { continue; } } if (!success) { alert("Failed. Try again."); } btn.innerHTML = 'Import'; btn.disabled = false; });